import { describe, expect, test } from "bun:test";
import { mkdtemp, mkdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { indexGoSource } from "../parser.js";
import { indexGoRepository } from "../repository.js";

describe("indexGoSource", () => {
  test("extracts declarations, calls, and a public router registration", () => {
    const indexed = indexGoSource(`
      package api
      import "github.com/gin-gonic/gin"
      // Service handles requests.
      type Service struct{}
      func (s *Service) Get(ctx *gin.Context) {}
      func Register(router *gin.Engine, s *Service) {
        router.GET("/items", s.Get)
      }
    `, "api/routes.go");
    expect(indexed.symbols.map((symbol) => symbol.qualifiedName)).toContain("Service.Get");
    expect(indexed.routes).toEqual(expect.arrayContaining([
      expect.objectContaining({ framework: "gin", method: "GET", path: "/items", handler: "s.Get" }),
    ]));
    expect(indexed.calls.some((call) => call.callee === "router.GET")).toBe(true);
  });

  test("keeps selector chains as structural call facts", () => {
    const indexed = indexGoSource(`
      package service
      import client "example.org/client"
      func Load() { client.Transport.Fetch() }
    `, "service/load.go");
    expect(indexed.calls).toEqual(expect.arrayContaining([
      expect.objectContaining({
        callee: "client.Transport.Fetch",
        selectorPath: ["client", "Transport", "Fetch"],
        importPath: "example.org/client",
        arguments: [],
      }),
    ]));
  });
});

describe("indexGoRepository", () => {
  test("scans selected roots and deterministically filters tests and generated files", async () => {
    const root = await mkdtemp(path.join(tmpdir(), "c4a-extract-go-"));
    await mkdir(path.join(root, "service"), { recursive: true });
    await mkdir(path.join(root, "other"), { recursive: true });
    await writeFile(path.join(root, "service", "main.go"), "package service\nfunc Start() {}\n");
    await writeFile(path.join(root, "service", "main_test.go"), "package service\nfunc TestStart() {}\n");
    await writeFile(path.join(root, "service", "generated.go"), "// Code generated by tool. DO NOT EDIT.\npackage service\n");
    await writeFile(path.join(root, "other", "ignored.go"), "package other\n");

    const indexed = await indexGoRepository(root, { include: ["service"] });

    expect(indexed.files.map((file) => file.path)).toEqual(["service/main.go"]);
    expect(indexed.stats).toEqual(expect.objectContaining({
      discoveredFiles: 3,
      analyzedFiles: 1,
      skippedTestFiles: 1,
      skippedGeneratedFiles: 1,
    }));
  });
});
