import { afterEach, describe, expect, test } from "bun:test";
import { mkdtemp, mkdir, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { indexGoRepository } from "../repository.js";

let root: string | undefined;
afterEach(async () => {
  if (root) await rm(root, { recursive: true, force: true });
  root = undefined;
});

describe("indexGoRepository options", () => {
  test("honors test, generated, include, custom exclusion, and symlink boundaries deterministically", async () => {
    root = await mkdtemp(path.join(tmpdir(), "extract-go-options-"));
    await mkdir(path.join(root, "service"), { recursive: true });
    await mkdir(path.join(root, "scratch"), { recursive: true });
    await mkdir(path.join(root, "external"), { recursive: true });
    await writeFile(path.join(root, "service", "z.go"), "package service\nfunc Zed() {}\n");
    await writeFile(path.join(root, "service", "a.go"), "package service\nfunc Alpha() {}\n");
    await writeFile(path.join(root, "service", "a_test.go"), "package service\nfunc TestAlpha() {}\n");
    await writeFile(path.join(root, "service", "generated.go"), "// Code generated by fixture. DO NOT EDIT.\npackage service\nfunc Generated() {}\n");
    await writeFile(path.join(root, "scratch", "ignored.go"), "package scratch\nfunc Ignore() {}\n");
    await writeFile(path.join(root, "external", "linked.go"), "package external\nfunc Linked() {}\n");
    await symlink(path.join(root, "external"), path.join(root, "service", "linked"));

    const indexed = await indexGoRepository(root, {
      include: ["service", "service"],
      includeTests: true,
      includeGenerated: true,
      excludeDirectories: ["scratch"],
      exportedOnly: true,
    });

    expect(indexed.files.map((file) => file.path)).toEqual([
      "service/a.go",
      "service/a_test.go",
      "service/generated.go",
      "service/z.go",
    ]);
    expect(indexed.options).toMatchObject({
      include: ["service"],
      includeTests: true,
      includeGenerated: true,
      exportedOnly: true,
    });
    expect(indexed.options.excludeDirectories).toEqual(expect.arrayContaining([".git", "node_modules", "scratch", "vendor"]));
    expect(indexed.stats).toMatchObject({
      discoveredFiles: 4,
      analyzedFiles: 4,
      skippedTestFiles: 0,
      skippedGeneratedFiles: 0,
    });
  });
});
