/** Maintained writing slots. Keys are identities; headings are reader guidance.
 * These declarations do not infer content or require every slot to be written. */
export const ARTICLE_BLUEPRINT_SLOTS: Record<string, string> = {
  c01: 'scope:定位与边界|capabilities:核心能力|dependencies:技术与依赖摘要|index:知识索引|tasks:任务导航|sources:来源与适用版本',
  c02: 'goals:业务目标|actors:角色与场景|prerequisites:使用前提|operations:操作与结果|exceptions:规则与异常|acceptance:验收依据|version:版本和范围|capabilities:能力边界|flows:主要流程入口|references:相关系统与文档',
  c03: 'scope:适用范围|terms:术语表|distinctions:易混概念|references:相关入口',
  c04: 'layers:依赖分层|catalog:核心依赖表|initialization:初始化与注入|compatibility:兼容和版本约束|boundaries:跨边界定位',
  c05: 'symptoms:现象索引|conditions:适用条件|findings:已知事实与判断|diagnosis:排查步骤|recovery:修复与验证|sources:来源',
  c06: 'context:背景与问题|decision:结论与状态|alternatives:选项与取舍|impact:影响范围|followup:后续行动|sources:来源与版本',
  c07: 'entries:问题到入口|identity:源码身份与版本|reading:推荐阅读顺序|boundaries:外部边界|evidence:进一步证据',
  f01: 'architecture:架构总览|stack:技术栈与运行方式|startup:启动与分层|crosscutting:关键横切能力|deployment:部署边界|references:相关入口',
  f02: 'organization:路由组织|routes:页面登记表|access:参数与访问控制|layout:布局和全局兜底|references:页面详情导航',
  f03: 'identity:页面定位|access:路由参数与权限|components:主要组件与依赖|flow:页面内流程|state:状态与数据流|api:API 边界|rules:业务条件|feedback:Loading Empty Error|references:知识与源码',
  f04: 'ownership:状态归属|initialization:初始化与读取|writes:写入与派生|async:异步与缓存|lifecycle:清理与生命周期|references:定位与排障',
  f05: 'clients:请求层与客户端|catalog:接口与调用入口|mapping:输入输出与转换|errors:错误与重试|boundaries:契约与外部边界|references:源码入口',
  f06: 'scope:模型范围|catalog:类型目录|roles:DTO 与视图模型|mapping:转换与校验|authority:权威与生成关系|references:使用与源码',
  f07: 'scope:复用范围|catalog:组件地图|parents:父页面与调用方|dependencies:封装与依赖库|references:详情与修改入口',
  f08: 'systems:使用的组件库与设计系统|layers:样式分层|tokens:Token 定义与消费|overrides:局部覆盖|platforms:主题与平台差异|accessibility:响应式与可访问性|examples:调整入口与示例|references:系统规范与源码',
  f09: 'scope:工程与交付边界|prerequisites:运行前提|commands:构建与测试入口|deployment:部署与配置|verification:验证与回滚|references:相关资料',
  f10: 'roles:宿主与 Remote|registration:注册与 Expose|loading:加载和生命周期|sharing:共享依赖与上下文|failures:错误与兼容边界|references:源码导航',
  f11: 'scope:子应用范围|catalog:子应用目录|ownership:入口与职责|integration:宿主接入|contracts:共享契约|capabilities:暴露能力与入口|navigation:页面与 API 导航|delivery:开发交付差异|details:详情与下一步',
  f12: 'purpose:职责与父层|callers:调用方与输入|behavior:行为与状态|dependencies:组件及请求依赖|change:修改入口|verification:测试与验证',
  d01: 'scope:领域职责|services:服务分工|entries:入口与调用边界|collaboration:数据与事件协作|references:阅读导航',
  d02: 'trigger:场景与触发|actors:参与方|flow:主流程|branches:分支与状态|failures:失败和下一步|sources:源码链路与证据边界',
  d03: 'scope:业务与版本|catalog:规则分类|conditions:条件与结果|implementation:执行位置|conflicts:例外与冲突|references:相关流程',
  d04: 'scope:工程边界|commands:构建与测试入口|delivery:环境与交付|conventions:兼容与研发约定|environment:运行与环境|configuration:配置定位|observability:日志指标与追踪|diagnosis:诊断路径|recovery:恢复与回滚|verification:验证依据',
  s01: 'scope:服务定位|startup:接入和启动|architecture:架构分层|capabilities:核心能力与接口|dependencies:模型和依赖摘要|index:知识索引|sources:源码位置',
  s02: 'scope:协议与范围|catalog:能力与入口表|authority:权威契约|implementation:调用方与实现|references:详情导航',
  s03: 'entry:用途与入口|validation:请求和边界校验|steps:处理步骤|downstream:数据与下游操作|response:响应与错误|concurrency:并发与幂等|references:调用方与入口',
  s04: 'scope:领域范围|catalog:实体与概念表|entities:核心实体|relations:已证实关系|states:状态与转移|rules:业务约束|references:实现与资料',
  s05: 'scope:存储职责|models:表与持久化对象|queries:查询和索引|cache:缓存与锁|consistency:事务与一致性|references:读写入口',
  s06: 'overview:依赖概览|requests:RPC 与 HTTP|events:事件与任务|storage:存储及配置服务|initialization:初始化与选择|failures:故障边界和下一步',
  s07: 'triggers:职责与触发源|registration:注册与订阅|payload:Payload 与过滤|processing:处理链路|retry:重试幂等与并发|reconciliation:检查点补偿与对账|operations:运行和观测入口',
  l01: 'purpose:用途与适用范围|installation:安装与初始化|capabilities:主要能力|usage:典型用法|contracts:契约与扩展点|limits:限制与兼容|references:源码与验证入口',
  l02: 'purpose:用途与选用|setup:接入与基本用法|scenarios:场景与变体|behavior:行为与组合规则|styles:样式与设计系统|limits:环境可访问性与限制|references:相关组件与源码入口',
  l03: 'scope:目标与适用范围|packages:平台软件包与版本|foundations:基础规范地图|components:组件与交互模式|configuration:主题及运行配置|adoption:采用定制与迁移|purpose:用途与语义|catalog:分类与 Token 目录|mapping:命名及对应关系|consumption:消费方式|rules:组合与适用规则|environment:环境与 Provider|globals:全局配置|inheritance:继承与局部覆盖|resources:CSS 与资源加载顺序|ssr:SSR 与 Hydration|platforms:平台和主题差异|verification:验证与排查入口|references:来源与修改入口',
  l04: 'boundary:扩展边界|registration:注册及执行顺序|context:输入输出与上下文|collaboration:宿主与下游协作|cleanup:错误和清理|references:使用与测试入口',
  l05: 'purpose:定位与适用平台|packages:软件包版本与维护状态|setup:安装与全局接入|catalog:组件分类与选择导航|configuration:公共配置资源与设计系统|compatibility:兼容迁移与限制|references:示例文档与源码',
  q01: 'scope:业务与质量范围|systems:系统与能力|navigation:测试资料导航|development:开发知识关联|tools:工具入口|strategy:测试策略|responsibility:职责与分层|risks:风险与重点|acceptance:验收依据|references:计划与执行入口',
  q02: 'scope:测试范围与目标|layers:测试分层|coverage:覆盖维度|collaboration:协作方式|risks:变更与风险|scenarios:验证场景|environment:环境与数据|execution:执行方式|acceptance:验收与退出条件',
  q03: 'scope:范围与来源|catalog:能力与场景表|prerequisites:前置条件和数据|automation:自动化入口|references:需求与缺陷',
  q04: 'context:适用范围与版本|smoke:冒烟场景集|selection:变更影响与回归选择|prerequisites:执行前提|records:结果记录入口|results:实际结果|failures:失败与阻塞|evidence:执行证据|conclusion:结论与限制|followup:后续处理',
  q05: 'requirements:数据需求|preparation:准备入口|isolation:环境和隔离|lifecycle:数据生命周期|verification:验证和清理',
  q06: 'tasks:任务到工具|prerequisites:接入前提|operations:常用操作|results:结果解释|references:代码与文档入口',
  q07: 'question:问题与场景|triggers:触发条件|cause:根因与证据|repair:修复和验证|prevention:防复发检查|scope:适用范围|answer:已确认结论|investigation:排查与证据|followup:待查与下一步|references:来源与相关知识',
};
