import { readFile } from "node:fs/promises";
import { dirname, extname } from "node:path";
import {
  computeDocumentContentHash,
  normalizeSnapshotRelativePath,
  type DocumentSnapshotAssetEntry,
  type DocumentSnapshotFileInput,
} from "@c4a/extract";
import { ErrorCategory } from "../lib/cliFeedback.js";
import { ContextError } from "../lib/errors.js";
import { ExitCode } from "../types/exitCode.js";

export const ROUTE_EVIDENCE_DOCUMENT_PATH = "__context_route_metadata.md";

export interface RouteHint {
  documentPath: string;
  route: string;
  metadataPath: string;
}

interface CapturedSourceFile {
  absolutePath: string;
  sourcePath: string;
  snapshotPath: string;
}

function countLines(markdown: string): number {
  if (markdown.length === 0) return 0;
  return markdown.endsWith("\n") ? markdown.split("\n").length - 1 : markdown.split("\n").length;
}

function runtimeError(message: string, detail: Record<string, unknown>): ContextError {
  return new ContextError(ExitCode.UserError, message, {
    category: ErrorCategory.UserInputInvalid,
    ...detail,
  });
}

function routePathForDocumentPath(path: string): string {
  const extension = extname(path);
  const withoutExtension = extension.length > 0 ? path.slice(0, -extension.length) : path;
  return `/${withoutExtension}`;
}

function parseRouteMetadata(raw: string, path: string): string[] {
  const parsed = JSON.parse(raw) as unknown;
  if (Array.isArray(parsed)) {
    return parsed.flatMap((item) => typeof item === "string" && item.trim().length > 0 ? [item.trim()] : []);
  }
  if (parsed !== null && typeof parsed === "object" && !Array.isArray(parsed)) {
    const record = parsed as Record<string, unknown>;
    const items = Array.isArray(record.items) ? record.items : Array.isArray(record.routes) ? record.routes : [];
    return items.flatMap((item) => typeof item === "string" && item.trim().length > 0 ? [item.trim()] : []);
  }
  throw new TypeError(`${path} must contain a string array, or an object with items/routes`);
}

function normalizeRouteHint(input: {
  route: string;
  metadataSourcePath: string;
  metadataSnapshotPath: string;
  snapshotPathBySourcePath: ReadonlyMap<string, string>;
}): { documentSourcePath: string; documentPath: string; route: string; metadataPath: string } {
  const { route, metadataSourcePath, metadataSnapshotPath, snapshotPathBySourcePath } = input;
  const normalized = route.replace(/^\.\//u, "").replace(/^\/+/u, "");
  const baseDir = dirname(metadataSourcePath) === "." ? "" : dirname(metadataSourcePath);
  const documentSourcePath = normalizeSnapshotRelativePath(`${baseDir.length > 0 ? `${baseDir}/` : ""}${normalized}.mdx`);
  const documentPath = snapshotPathBySourcePath.get(documentSourcePath) ?? documentSourcePath;
  return {
    documentSourcePath,
    documentPath,
    route: `/${documentSourcePath.slice(0, -extname(documentSourcePath).length)}`,
    metadataPath: metadataSnapshotPath,
  };
}

export function routeForDocument(input: {
  sourcePath: string;
  documentPath: string;
  routeHints: ReadonlyMap<string, RouteHint>;
}): { route: string; metadataPath?: string } | undefined {
  const hinted = input.routeHints.get(input.sourcePath);
  if (hinted !== undefined) return hinted;
  if (extname(input.documentPath).toLowerCase() === ".mdx") {
    return { route: routePathForDocumentPath(input.sourcePath) };
  }
  return undefined;
}

export function routeEvidenceMarkdown(routeHints: ReadonlyMap<string, RouteHint>): string {
  const entries = Array.from(routeHints.entries())
    .sort(([, left], [, right]) => left.documentPath.localeCompare(right.documentPath));
  const lines = [
    "# Document site route metadata",
    "",
    "This file is generated by Context from captured document-site route metadata. It records routes as evidence; it is not authored by an agent.",
    "",
  ];
  for (const [documentSourcePath, hint] of entries) {
    lines.push(
      `## ${hint.route}`,
      "",
      `- Route: ${hint.route}`,
      `- Canonical route form: ${hint.route} (no .html suffix)`,
      `- Document source file: ${hint.documentPath}`,
      ...(documentSourcePath !== hint.documentPath ? [`- Original document path: ${documentSourcePath}`] : []),
      `- Route metadata file: ${hint.metadataPath}`,
      "",
    );
  }
  return lines.join("\n");
}

export function routeEvidenceSnapshot(routeHints: ReadonlyMap<string, RouteHint>): {
  file: DocumentSnapshotFileInput;
  document: {
    path: string;
    title: string;
    line_count: number;
  };
} | null {
  if (routeHints.size === 0) return null;
  const markdown = routeEvidenceMarkdown(routeHints);
  return {
    file: {
      path: ROUTE_EVIDENCE_DOCUMENT_PATH,
      bytes: markdown,
      title: "Document site route metadata",
    },
    document: {
      path: ROUTE_EVIDENCE_DOCUMENT_PATH,
      title: "Document site route metadata",
      line_count: countLines(markdown),
    },
  };
}

export async function readRouteMetadataFiles(input: {
  files: CapturedSourceFile[];
  sourceName: string;
  local: string;
  snapshotPathBySourcePath: ReadonlyMap<string, string>;
}): Promise<{
  assets: DocumentSnapshotAssetEntry[];
  metadataFiles: Array<{
    path: string;
    routes: string[];
  }>;
  routeHints: Map<string, RouteHint>;
  rawByPath: Map<string, string>;
}> {
  const assets: DocumentSnapshotAssetEntry[] = [];
  const metadataFiles: Array<{ path: string; routes: string[] }> = [];
  const routeHints = new Map<string, RouteHint>();
  const rawByPath = new Map<string, string>();
  for (const file of input.files) {
    let raw: string;
    try {
      raw = await readFile(file.absolutePath, "utf8");
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      throw runtimeError(`file source ${input.sourceName} metadata read failed: ${file.snapshotPath}: ${message}`, {
        sourceName: input.sourceName,
        local: input.local,
        path: file.snapshotPath,
        next: `fix file permissions or update sources/file/index.yaml include for ${input.sourceName}, then rerun context run capture:file:${input.sourceName}`,
      });
    }
    let routes: string[];
    try {
      routes = parseRouteMetadata(raw, file.snapshotPath);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      throw runtimeError(`file source ${input.sourceName} route metadata is invalid: ${file.snapshotPath}: ${message}`, {
        sourceName: input.sourceName,
        local: input.local,
        path: file.snapshotPath,
        next: `fix ${file.snapshotPath} or remove it from include before rerunning capture`,
      });
    }
    assets.push({
      path: file.snapshotPath,
      content_hash: computeDocumentContentHash(raw),
      media_type: "application/json",
      source: {
        kind: "route-metadata",
        ...(file.sourcePath !== file.snapshotPath ? { source_path: file.sourcePath } : {}),
      },
    });
    metadataFiles.push({ path: file.snapshotPath, routes });
    rawByPath.set(file.snapshotPath, raw);
    for (const route of routes) {
      const hint = normalizeRouteHint({
        route,
        metadataSourcePath: file.sourcePath,
        metadataSnapshotPath: file.snapshotPath,
        snapshotPathBySourcePath: input.snapshotPathBySourcePath,
      });
      routeHints.set(hint.documentSourcePath, {
        documentPath: hint.documentPath,
        route: hint.route,
        metadataPath: hint.metadataPath,
      });
    }
  }
  return { assets, metadataFiles, routeHints, rawByPath };
}
