import type { ProjectLanguage } from "./workspace.js";

export function renderProjectEntry(language: ProjectLanguage): string {
  if (language === "zh-CN") {
    return [
      'import { defineProject } from "@c4a/context";',
      "",
      "// 使用 `context source add ...` 添加 repo/file/lark 来源，然后在此声明阶段。",
      "// `context status --format json` 会选择当前步骤所需的流程文档。",
      "// SDK 文档：node_modules/@c4a/context/docs/reference/project-api.md",
      "// 输出可多选；新工作区默认知识包＋网站，由 Agent 在打包配置步骤声明 site。",
      "// 包输出指南：node_modules/@c4a/context/docs/guides/package-outputs.md",
      "// 包模板：node_modules/@c4a/context/docs/reference/package-templates.md",
      "",
      "export default defineProject({",
      "  sources: [],",
      "  phases: [],",
      "  packages: [],",
      "});",
      "",
    ].join("\n");
  }
  return [
    'import { defineProject } from "@c4a/context";',
    "",
    "// Add repo/file/lark sources with `context source add ...`, then declare phases here.",
    "// Step-specific procedures are selected by `context status --format json`.",
    "// SDK docs: node_modules/@c4a/context/docs/reference/project-api.md",
    "// Package output guide: node_modules/@c4a/context/docs/guides/package-outputs.md",
    "// Package templates: node_modules/@c4a/context/docs/reference/package-templates.md",
    "// Configure knowledge authoring in src/indexers.yaml.",
    "// Keep phases for capture or a genuinely project-specific non-Indexer operation.",
    "// packages: [",
    "//   // Output channels support multiple selection; the new-workspace default is KB + website.",
    "//   // Honor explicit output choices; add llmsPackage when LLM text is also selected.",
    '//   kbPackage({ name: "sample-lib-kb", site: {}, template: { path: "src/package-templates/kb", vars: { displayName: "Sample Library KB" } } }),',
    "// ],",
    "",
    "export default defineProject({",
    "  sources: [],",
    "  phases: [],",
    "  packages: [],",
    "});",
    "",
  ].join("\n");
}

export function renderReadme(projectName: string, language: ProjectLanguage): string {
  if (language === "zh-CN") {
    return [
      `# ${projectName}`,
      "",
      "这是一个项目内的 Context 工作区。",
      "",
      "## 初始化",
      "",
      "```bash",
      "mkdir -p .tmp/install",
      'TMPDIR="$PWD/.tmp/install" bun install',
      "context status --format json",
      "```",
      "",
      "使用 `context plugin install` 安装或刷新全局 Agent 集成。后续以状态返回的合法命令、门禁和手册为准，不要根据记忆选择生命周期命令。",
      "",
      "## 目录",
      "",
      "- `src/index.ts`：来源、阶段和输出包声明。",
      "- `src/package-templates/`：输出包模板。",
      "- `sources/`：来源注册信息和采集快照。",
      "- `knowledge/`：持久知识及其结构投影。",
      "- `dist/`：生成的知识包。",
      "- `.tmp/agent-payloads/`：Agent 可选的临时命令输入；初始化时会创建，被清理后可在写入前重新创建。",
      "- `.tmp/install/`：依赖安装使用的工作区本地临时目录。",
      "- `.tmp/context-runtime/`：可删除的 Context 运行时状态。",
      "",
      "不要创建另一个隐藏 Context 工作区，也不要手工修改生命周期状态。",
      "",
      "## 手册",
      "",
      "优先阅读 `context status --format json` 为当前步骤选择的资源。通用 SDK 文档入口：",
      "",
      "- `node_modules/@c4a/context/docs/README.md`",
      "- `node_modules/@c4a/context/docs/reference/project-api.md`",
      "- `node_modules/@c4a/context/docs/reference/package-templates.md`",
      "",
    ].join("\n");
  }
  return [
    `# ${projectName}`,
    "",
    "This is a project-local Context workspace.",
    "",
    "## Setup",
    "",
    "```bash",
    "mkdir -p .tmp/install",
    'TMPDIR="$PWD/.tmp/install" bun install',
    "context status --format json",
    "```",
    "",
    "Install or refresh the global Agent integration with `context plugin install`. The current status response selects the legal commands, gates, and manuals for the next step; do not choose lifecycle commands from a memorized sequence.",
    "",
    "## Project Layout",
    "",
    "- `src/index.ts`: source, phase, and package declarations.",
    "- `src/package-templates/`: package output templates.",
    "- `sources/`: registered sources and captured snapshots.",
    "- `knowledge/`: durable approved knowledge and its structural projection with minimal closed source inputs.",
    "- `dist/`: generated packages.",
    "- `.tmp/agent-payloads/`: optional Agent-owned command inputs. Initialization creates it; recreate it before writing if scratch cleanup removed it.",
    "- `.tmp/install/`: workspace-local temporary files used during dependency installation.",
    "- `.tmp/context-runtime/`: disposable runtime files, including lifecycle candidates and staged structures. Successful close removes completed lifecycle and Review state.",
    "",
    "Do not create another hidden Context workspace or edit lifecycle-managed state by hand.",
    "",
    "## Manuals",
    "",
    "Use the resources selected by `context status --format json` for step-specific instructions. General SDK documentation starts at:",
    "",
    "- `node_modules/@c4a/context/docs/README.md`",
    "- `node_modules/@c4a/context/docs/reference/project-api.md`",
    "- `node_modules/@c4a/context/docs/reference/package-templates.md`",
    "",
  ].join("\n");
}

export function renderAgents(projectName: string, language: ProjectLanguage): string {
  if (language === "zh-CN") {
    return [
      `# ${projectName} Context 项目`,
      "",
      "这是项目内的 Context 工作区。`src/` 保存人工维护的项目声明和包模板；`sources/`、`knowledge/`、`dist/` 与 `.tmp/context-runtime/` 由 Context 生命周期管理。",
      "",
      "## 工作目录",
      "",
      "本文件所在目录是本次 Context 工作区根目录，对应 `package.json` 中的 `context.project: true`。执行 Context 工作流 CLI 时，每次 shell 调用都必须明确使用这个目录作为工作目录；不要假设前一次 `cd` 会保留，恢复会话后也一样。",
      "",
      "本次工作的 `.tmp/agent-payloads/`、开工报告和 `.tmp/context-runtime/` 都归属这个工作区。生成和读取这些内容时使用工作区内的路径；不能把父目录或其他工作区的 `.tmp/` 当成本次临时目录。材料来源可以位于其他目录，但来源目录不决定工作区。",
      "",
      "若 CLI 的工作区、Route 资源所在工作区与本次 `.tmp/` 不一致，说明命令执行、文件生成或读取位置有误：停止提交，按 CLI 提示核对工作目录，再获取该工作区的当前 Route。父目录即使也是 Context 工作区，也不能混用 revision、任务或账本；不要靠移动运行时文件或新建工作区来消除报错。",
      "",
      "## 工作区契约",
      "",
      "版本以 package.json.version 为准。正式内容变化收尾时通过 context version inspect / record 同步递增版本并生成 changelog.yaml 和 CHANGELOG.md，具体说明由 Agent 根据 diff 和会话撰写。新增模块或扩大知识覆盖升 minor，普通修补、目录和正式状态变化升 patch；major 只由人工明确指定。.tmp 进度不算变化，build 只记录 hash。仅主协调者记录版本，不自动 commit 或发布。触发来源必填；触发用户优先使用会话中明确的飞书显示名，否则由 CLI 读取 Git 用户名。",
      "每个版本的 Changelog 详情不得超过 1500 字：标题、变更列表、触发来源说明及用户显示名的可见字符合计计数，含标点，不计协议字段名、版本号和日期。超出时由 Agent 在提交前合并同类变化、删除重复过程描述，压缩至上限内；保留主要变化、影响和触发来源，不直接截断，也不把一轮拆成多个版本规避限制。",
      "",
      "- 通过已安装的 Context Skill 开始或恢复工作；直接使用 CLI 时，从 `context status --format json` 开始。",
      "- 将 `workflow.current` 及其选择的资源和命令视为当前步骤的唯一权威。不要根据本文件、旧会话或记忆重建生命周期流程。",
      "- Route 返回 `configuration` 时，只修改它指定的项目文件。所有生命周期写入必须使用 Context CLI；可以正常阅读面向用户的知识页和产物，但不得用临时脚本修补或改写受管理目录。",
      "- 来源、语义结构、Review 和包形态等决定必须来自用户或当前 Route 已建立的授权，不得从仓库布局、文件名或示例推断。",
      "- Context 完成只证明知识工作流状态，不证明 Git 提交范围安全。保留任务开始前已有的工作树变更，只按明确路径暂存；不要用 `git add -A` 把无关修改、删除或未跟踪目录带入提交。",
      "- 发布知识包前可按产品需要定制 `src/package-templates/kb/wikis/index.md`；不要编辑生成后的 `dist/` 页面。",
      "",
      "## 图表风格（可修改）",
      "",
      "- 默认简约：约 1px 细线；文字与线条使用随主题变化的默认色，不加彩色装饰。Mermaid 不硬编码调色板、背景或主题初始化；线宽由支持它的展示端设置，不因此阻塞写作。",
      "- 本节可由用户修改，Agent 遵循当前 AGENTS.md 和本次明确要求。来源颜色若承载含义，应转为文字或图例，不能直接丢弃。",
      "- package.json 的 context.convertVisuals 默认开启。对能保真表达的结构图/表尝试转换；无读图能力或不适合时保留原图。本次会话明确关闭优先于默认设置。",
      "",
      "## 手册",
      "",
      "- 只读取 `workflow.current.resources` 为当前步骤选择的手册和 Schema。",
      "- SDK 总入口：`node_modules/@c4a/context/docs/README.md`。",
      "- 项目声明：`node_modules/@c4a/context/docs/reference/project-api.md`。",
      "- 包模板：`node_modules/@c4a/context/docs/reference/package-templates.md`。",
      "",
    ].join("\n");
  }
  return [
    `# ${projectName} Context Project`,
    "",
    "This is a project-local Context workspace. `src/` contains human-maintained project declarations and package templates; `sources/`, `knowledge/`, `dist/`, and `.tmp/context-runtime/` are lifecycle-managed by Context.",
    "",
    "## Working Directory",
    "",
    "The directory containing this file is this Context workspace root, identified by `context.project: true` in its package.json. Set it explicitly as the working directory of every workflow CLI call, including after conversation resume. A previous shell `cd` may not persist.",
    "",
    "Keep this task's `.tmp/agent-payloads/`, work-start report, and `.tmp/context-runtime/` in this workspace. Generate and read them using workspace-local paths, never a parent or another workspace's `.tmp/`. Source material may live elsewhere; its location does not select the workspace.",
    "",
    "If the CLI workspace, Route resources, and task scratch directory refer to different workspaces, a command, write, or read is targeting the wrong location. Stop submissions, follow the CLI working-directory diagnostic, and obtain the intended workspace's current Route. Even an initialized parent is a separate workspace: do not mix revisions, tasks, or ledgers, move runtime state, or initialize another workspace to clear the error.",
    "",
    "## Workspace Contract",
    "",
    "package.json.version is the workspace version. At formal-content completion, use context version inspect / record to increment SemVer and generate changelog.yaml and CHANGELOG.md together. Write descriptions from the diff and conversation. Added modules/coverage increment minor; repairs, navigation and persistent status changes increment patch. Major requires an explicit user instruction. Ignore .tmp progress; build only records hashes. The coordinator alone records versions, without automatic commits or publishing. Triggers are required; use an explicitly known conversational Lark display name, otherwise let CLI use Git user.name.",
    "Each version's changelog details must total at most 1500 visible characters, including punctuation across the title, changes, trigger descriptions and user display name; exclude protocol keys, version and date. Before submission, compress longer entries by merging related changes and removing repeated process narration. Preserve the main changes, impact and triggers; never truncate blindly or split one iteration into multiple versions to evade the limit.",
    "",
    "- Start or resume through the installed Context Skill. When using the CLI directly, begin with `context status --format json`.",
    "- Treat `workflow.current` and its selected resources and commands as the only current-step authority. Do not reconstruct the lifecycle from this file, an earlier conversation, or memory.",
    "- When the Route returns `configuration`, edit only the named project files. Use Context CLI for every lifecycle write. User-facing knowledge pages and outputs may be read normally, but managed directories must never be repaired or rewritten with ad hoc scripts.",
    "- Source, semantic-structure, Review, and package-shape decisions require user authority or authority established by the current Route. Never infer them from repository layout, filenames, or examples.",
    "- Context completion proves knowledge-workflow state, not Git commit safety. Preserve worktree changes that existed before the task, stage only explicit paths, and never use `git add -A` to mix unrelated modifications, deletions, or untracked directories into the deliverable.",
    "- Customize `src/package-templates/kb/wikis/index.md` for the product before publishing a knowledge package; do not edit generated `dist/` pages.",
    "",
    "## Diagram style (user editable)",
    "",
    "- Keep diagrams minimal: approximately 1px lines, theme-default text and stroke colors, no colorful decoration. Avoid fixed Mermaid palettes, backgrounds and theme initialization. Configure line width in a capable viewer; unsupported styling never blocks authoring.",
    "- Follow this editable AGENTS.md and explicit current user instructions. Preserve meaningful source colors as labels or a legend instead of discarding their meaning.",
    "- package.json context.convertVisuals defaults to true. Attempt faithful structural diagram/table conversion when capable; otherwise retain the original. Explicit session opt-out overrides the saved default.",
    "",
    "## Manuals",
    "",
    "- Read only the manuals and schemas selected by `workflow.current.resources` for the current step.",
    "- General SDK index: `node_modules/@c4a/context/docs/README.md`.",
    "- Project declarations: `node_modules/@c4a/context/docs/reference/project-api.md`.",
    "- Package templates: `node_modules/@c4a/context/docs/reference/package-templates.md`.",
    "",
  ].join("\n");
}
