import type { ProjectLanguage } from "./workspace.js";

export function renderProjectEntry(language: ProjectLanguage): string {
  if (language === "zh-CN") {
    return [
      'import { defineProject } from "@c4a/context";',
      "",
      "// 使用 `context source add ...` 添加 repo/file/lark 来源，然后在此声明阶段。",
      "// `context status --format json` 会选择当前步骤所需的流程文档。",
      "// SDK 文档：node_modules/@c4a/context/docs/reference/project-api.md",
      "// 包输出指南：node_modules/@c4a/context/docs/guides/package-outputs.md",
      "// 包模板：node_modules/@c4a/context/docs/reference/package-templates.md",
      "",
      "export default defineProject({",
      "  sources: [],",
      "  phases: [],",
      "  packages: [],",
      "});",
      "",
    ].join("\n");
  }
  return [
    'import { defineProject } from "@c4a/context";',
    "",
    "// Add repo/file/lark sources with `context source add ...`, then declare phases here.",
    "// Step-specific procedures are selected by `context status --format json`.",
    "// SDK docs: node_modules/@c4a/context/docs/reference/project-api.md",
    "// Package output guide: node_modules/@c4a/context/docs/guides/package-outputs.md",
    "// Package templates: node_modules/@c4a/context/docs/reference/package-templates.md",
    "// Configure knowledge authoring in src/indexers.yaml.",
    "// Keep phases for capture or a genuinely project-specific non-Indexer operation.",
    "// packages: [",
    "//   // Add one package only after the user chooses the output shape and templates.",
    "//   // Recommended first output is a kb package; add llms later only after confirmation.",
    '//   kbPackage({ name: "sample-lib-kb", template: { path: "src/package-templates/kb", vars: { displayName: "Sample Library KB" } } }),',
    "// ],",
    "",
    "export default defineProject({",
    "  sources: [],",
    "  phases: [],",
    "  packages: [],",
    "});",
    "",
  ].join("\n");
}

export function renderReadme(projectName: string, language: ProjectLanguage): string {
  if (language === "zh-CN") {
    return [
      `# ${projectName}`,
      "",
      "这是一个项目内的 Context 工作区。",
      "",
      "## 初始化",
      "",
      "```bash",
      "mkdir -p .tmp/install",
      'TMPDIR="$PWD/.tmp/install" bun install',
      "context status --format json",
      "```",
      "",
      "使用 `context plugin install` 安装或刷新全局 Agent 集成。后续以状态返回的合法命令、门禁和手册为准，不要根据记忆选择生命周期命令。",
      "",
      "## 目录",
      "",
      "- `src/index.ts`：来源、阶段和输出包声明。",
      "- `src/package-templates/`：输出包模板。",
      "- `sources/`：来源注册信息和采集快照。",
      "- `knowledge/`：持久知识及其结构投影。",
      "- `dist/`：生成的知识包。",
      "- `.tmp/agent-payloads/`：Agent 可选的临时命令输入；初始化时会创建，被清理后可在写入前重新创建。",
      "- `.tmp/install/`：依赖安装使用的工作区本地临时目录。",
      "- `.tmp/context-runtime/`：可删除的 Context 运行时状态。",
      "",
      "不要创建另一个隐藏 Context 工作区，也不要手工修改生命周期状态。",
      "",
      "## 手册",
      "",
      "优先阅读 `context status --format json` 为当前步骤选择的资源。通用 SDK 文档入口：",
      "",
      "- `node_modules/@c4a/context/docs/README.md`",
      "- `node_modules/@c4a/context/docs/reference/project-api.md`",
      "- `node_modules/@c4a/context/docs/reference/package-templates.md`",
      "",
    ].join("\n");
  }
  return [
    `# ${projectName}`,
    "",
    "This is a project-local Context workspace.",
    "",
    "## Setup",
    "",
    "```bash",
    "mkdir -p .tmp/install",
    'TMPDIR="$PWD/.tmp/install" bun install',
    "context status --format json",
    "```",
    "",
    "Install or refresh the global Agent integration with `context plugin install`. The current status response selects the legal commands, gates, and manuals for the next step; do not choose lifecycle commands from a memorized sequence.",
    "",
    "## Project Layout",
    "",
    "- `src/index.ts`: source, phase, and package declarations.",
    "- `src/package-templates/`: package output templates.",
    "- `sources/`: registered sources and captured snapshots.",
    "- `knowledge/`: durable approved knowledge and its structural projection with minimal closed source inputs.",
    "- `dist/`: generated packages.",
    "- `.tmp/agent-payloads/`: optional Agent-owned command inputs. Initialization creates it; recreate it before writing if scratch cleanup removed it.",
    "- `.tmp/install/`: workspace-local temporary files used during dependency installation.",
    "- `.tmp/context-runtime/`: disposable runtime files, including lifecycle candidates and staged structures. Successful close removes completed lifecycle and Review state.",
    "",
    "Do not create another hidden Context workspace or edit lifecycle-managed state by hand.",
    "",
    "## Manuals",
    "",
    "Use the resources selected by `context status --format json` for step-specific instructions. General SDK documentation starts at:",
    "",
    "- `node_modules/@c4a/context/docs/README.md`",
    "- `node_modules/@c4a/context/docs/reference/project-api.md`",
    "- `node_modules/@c4a/context/docs/reference/package-templates.md`",
    "",
  ].join("\n");
}

export function renderAgents(projectName: string, language: ProjectLanguage): string {
  if (language === "zh-CN") {
    return [
      `# ${projectName} Context 项目`,
      "",
      "这是项目内的 Context 工作区。`src/` 保存人工维护的项目声明和包模板；`sources/`、`knowledge/`、`dist/` 与 `.tmp/context-runtime/` 由 Context 生命周期管理。",
      "",
      "## 工作区契约",
      "",
      "- 通过已安装的 Context Skill 开始或恢复工作；直接使用 CLI 时，从 `context status --format json` 开始。",
      "- 将 `workflow.current` 及其选择的资源和命令视为当前步骤的唯一权威。不要根据本文件、旧会话或记忆重建生命周期流程。",
      "- Route 返回 `configuration` 时，只修改它指定的项目文件。所有生命周期写入必须使用 Context CLI；可以正常阅读面向用户的知识页和产物，但不得用临时脚本修补或改写受管理目录。",
      "- 来源、语义结构、Review 和包形态等决定必须来自用户或当前 Route 已建立的授权，不得从仓库布局、文件名或示例推断。",
      "- Context 完成只证明知识工作流状态，不证明 Git 提交范围安全。保留任务开始前已有的工作树变更，只按明确路径暂存；不要用 `git add -A` 把无关修改、删除或未跟踪目录带入提交。",
      "- 发布知识包前可按产品需要定制 `src/package-templates/kb/wikis/index.md`；不要编辑生成后的 `dist/` 页面。",
      "",
      "## 手册",
      "",
      "- 只读取 `workflow.current.resources` 为当前步骤选择的手册和 Schema。",
      "- SDK 总入口：`node_modules/@c4a/context/docs/README.md`。",
      "- 项目声明：`node_modules/@c4a/context/docs/reference/project-api.md`。",
      "- 包模板：`node_modules/@c4a/context/docs/reference/package-templates.md`。",
      "",
    ].join("\n");
  }
  return [
    `# ${projectName} Context Project`,
    "",
    "This is a project-local Context workspace. `src/` contains human-maintained project declarations and package templates; `sources/`, `knowledge/`, `dist/`, and `.tmp/context-runtime/` are lifecycle-managed by Context.",
    "",
    "## Workspace Contract",
    "",
    "- Start or resume through the installed Context Skill. When using the CLI directly, begin with `context status --format json`.",
    "- Treat `workflow.current` and its selected resources and commands as the only current-step authority. Do not reconstruct the lifecycle from this file, an earlier conversation, or memory.",
    "- When the Route returns `configuration`, edit only the named project files. Use Context CLI for every lifecycle write. User-facing knowledge pages and outputs may be read normally, but managed directories must never be repaired or rewritten with ad hoc scripts.",
    "- Source, semantic-structure, Review, and package-shape decisions require user authority or authority established by the current Route. Never infer them from repository layout, filenames, or examples.",
    "- Context completion proves knowledge-workflow state, not Git commit safety. Preserve worktree changes that existed before the task, stage only explicit paths, and never use `git add -A` to mix unrelated modifications, deletions, or untracked directories into the deliverable.",
    "- Customize `src/package-templates/kb/wikis/index.md` for the product before publishing a knowledge package; do not edit generated `dist/` pages.",
    "",
    "## Manuals",
    "",
    "- Read only the manuals and schemas selected by `workflow.current.resources` for the current step.",
    "- General SDK index: `node_modules/@c4a/context/docs/README.md`.",
    "- Project declarations: `node_modules/@c4a/context/docs/reference/project-api.md`.",
    "- Package templates: `node_modules/@c4a/context/docs/reference/package-templates.md`.",
    "",
  ].join("\n");
}
