import type { CommandMatrixEntry } from "./pathFreeContractTypes.js";

export const COMMAND_MATRIX: readonly CommandMatrixEntry[] = [
  { command: "version", view: "production-semantic", handles: ["version"], notes: "Knowledge workspace version namespace." },
  { command: "version inspect", view: "production-semantic", handles: ["version", "expected_digest"], notes: "Inspects formal changes before recording a version." },
  { command: "version record", view: "production-semantic", handles: ["version", "expected_digest"], notes: "Atomically records an increasing version and agent-written changelog." },
  { command: "version publish-check", view: "production-semantic", handles: ["version", "hash"], notes: "Checks built artifacts against the successful publication baseline without uploading." },
  { command: "version published", view: "production-semantic", handles: ["version", "hash", "receipt"], notes: "Records an explicitly supplied successful external publication receipt." },
  { command: "entry", view: "production-semantic", handles: ["project_status", "workspace_root", "next_command"], notes: "Resolves the single agent entry into initialization, workspace relocation, or current Agent Graph workflow evaluation." },
  { command: "init", view: "production-semantic", handles: ["project_dir", "project_name"], notes: "Creates a project-local Context workspace." },
  { command: "plugin", view: "production-semantic", handles: ["plugin_status", "agent_adapter"], notes: "Global Context agent plugin namespace." },
  { command: "plugin install", view: "production-semantic", handles: ["plugin_status", "agent_adapter", "marketplace_root"], notes: "Installs or refreshes bundled global agent plugins." },
  { command: "plugin path", view: "production-semantic", handles: ["marketplace_root"], notes: "Prints the bundled plugin marketplace root." },
  { command: "plugin status", view: "production-semantic", handles: ["plugin_status", "agent_adapter"], notes: "Reports global plugin installation state and stale entry cleanup." },
  { command: "debug", view: "production-semantic", handles: ["trace_id", "debug_status"], notes: "Workspace-local observational trace namespace; disabled by default." },
  { command: "debug enable", view: "production-semantic", handles: ["trace_id", "debug_status"], notes: "Explicitly enables command and Agent Graph event recording below the ignored workspace runtime directory." },
  { command: "debug disable", view: "production-semantic", handles: ["trace_id", "debug_status"], notes: "Stops new event recording without deleting prior trace data." },
  { command: "debug status", view: "production-semantic", handles: ["trace_id", "debug_status", "event_count"], notes: "Reports debug configuration, event counts, and local trace locations." },
  { command: "debug export", view: "production-semantic", handles: ["trace_id", "event_count", "transition_count"], notes: "Deterministically projects append-only events into replay-ready JSON below the workspace runtime directory." },
  { command: "logs", view: "production-semantic", handles: ["delivery_status"], notes: "Hidden namespace for a configured package-owned runtime event sink." },
  { command: "logs plan", view: "production-semantic", handles: ["outbox", "event_summary", "sink_destination", "next_command"], notes: "Describes the fixed runtime-event payload source and package-owned sink without delivering data." },
  { command: "logs flush", view: "production-semantic", handles: ["delivery_status", "event_count", "next_command"], notes: "Flushes pending generic runtime events through the configured package-owned sink." },
  { command: "revise", view: "production-semantic", handles: ["view_ref", "revision_status", "next_command"], notes: "Starts one source-faithful conversational correction by approved title, path, ViewRef, NodeRef, or fragment id." },
  { command: "revise", view: "production-semantic", handles: ["candidate_id", "path", "repair_intent_digest"], notes: "Reopens the Author workset that owns one current Candidate and invalidates only its derived outputs." },

  { command: "update", view: "production-semantic", handles: ["revision", "source_ref", "next_command"], notes: "Prepare a scoped update from fixed source inputs and approved knowledge." },
  { command: "task", view: "production-semantic", handles: ["revision", "source_ref", "next_command"], notes: "Current task adjustment and explicit rollback namespace." },
  { command: "task prepare", view: "production-semantic", handles: ["state", "next_command"], notes: "Prepare an explicitly requested workspace maintenance reset while retaining approved knowledge and registered sources." },
  { command: "task recover", view: "production-semantic", handles: ["resources", "actions", "revision", "affected_worksets", "next"], notes: "Independent diagnostics and digest-bound draft recovery; sanitized issue template when safe recovery is unavailable." },
  { command: "task resume", view: "production-semantic", handles: ["action", "next"], notes: "Explicitly reopen a cleared task from current requirements while preserving retained knowledge and any active ledger." },
  { command: "task maintain", view: "production-semantic", handles: ["id", "targets", "timing", "next_command"], notes: "Registers approved-page maintenance without replacing active production." },
  { command: "task maintenance-status", view: "production-semantic", handles: ["revision", "state", "reason"], notes: "Reads active and queued maintenance and its current transition revision." },
  { command: "task advance-maintenance", view: "production-semantic", handles: ["revision", "outcome", "next_command"], notes: "Executes the Graph-selected transition at a safe delivery boundary." },
  { command: "task cancel-maintenance", view: "production-semantic", handles: ["id", "revision", "outcome", "next_command"], notes: "Cancels pending maintenance or explicitly discards only its current unfinished drafts." },
  { command: "task adjust", view: "production-semantic", handles: ["revision", "source_ref", "next_command"], notes: "Invalidate selected current source worksets while retaining peers." },
  { command: "task rollback", view: "production-semantic", handles: ["revision", "source_ref", "next_command"], notes: "Preview and apply explicitly selected rollback bytes." },
  { command: "task retire", view: "production-semantic", handles: ["revision", "targets", "blockers", "next_command"], notes: "Preview and atomically retire approved articles with reference cleanup and a temporary restore input." },
  { command: "task finish-rollback", view: "production-semantic", handles: ["revision", "source_ref", "next_command"], notes: "Finish rollback cleanup after close and build." },
  { command: "source import", view: "production-semantic", handles: ["revision", "source_ref", "next_command"], notes: "Import managed Markdown or prefetched Lark responses." },
  { command: "source rename", view: "production-semantic", handles: ["revision", "source_ref", "next_command"], notes: "Preview and apply an exact managed source rename with references." },
  { command: "status", view: "production-semantic", handles: ["project_status", "source_name", "phase_id", "next_command"], notes: "Reports project lifecycle state and status-driven next actions." },
  { command: "action", view: "production-semantic", handles: ["project_status", "next_command"], notes: "Current workflow Action completion namespace." },
  { command: "action prepare-current", view: "production-semantic", handles: ["project_status", "input_payload"], notes: "Prepares current stage task directories without resubmitting accepted work." },
  { command: "action complete-current", view: "production-semantic", handles: ["project_status", "input_payload", "next_command"], notes: "Submits one revision-bound result for the exact current workflow Action." },
  { command: "resource", view: "production-semantic", handles: ["project_status"], notes: "Context workflow resource namespace." },
  { command: "resource acknowledge-current", view: "production-semantic", handles: ["project_status", "resource_digest", "next_command"], notes: "Records one merged current-conversation receipt set after the Agent reads every direct required resource." },
  { command: "resource materialize", view: "production-semantic", handles: ["project_status", "source_name", "phase_id", "next_command"], notes: "Materializes one route-selected Context view for the current workflow revision." },
  { command: "indexer", view: "production-semantic", handles: ["indexer_status"], notes: "Indexer requirement, discovery, selection, and Provider resolution namespace." },
  { command: "indexer catalog", view: "production-semantic", handles: ["skill_name", "skill_entry"], notes: "Lists bundled skill entry metadata without versions or integrity checks; does not declare Agent capabilities." },
  { command: "indexer report-benchmark", view: "production-semantic", handles: ["benchmark_manifest", "current_authority", "observation", "oracle_evaluation", "override", "benchmark_report"], notes: "Loads the read-only oracle only after execution from outside the Agent workspace and emits the recomputable ten-field forward-test report." },
  { command: "package", view: "production-semantic", handles: ["package_name", "package_status"], notes: "Package output configuration namespace." },
  { command: "package template", view: "production-semantic", handles: ["package_name", "template_status"], notes: "Package template review namespace." },
  { command: "package template accept", view: "production-semantic", handles: ["package_name", "template_status"], notes: "Explicitly accepts an unchanged generated starter template." },
  { command: "run", view: "production-semantic", handles: ["phase_id", "view", "source_ref", "node_ref", "view_ref", "input_payload"], notes: "Inspects, validates, stages, or executes declared project phases." },
  { command: "review", view: "production-semantic", handles: ["candidate_id", "review_status"], notes: "Review namespace for draft project candidates." },
  { command: "review html", view: "production-semantic", handles: ["candidate_id", "review_status", "source_ref"], notes: "Renders self-contained review UI and copyable review payload." },
  { command: "review list", view: "production-semantic", handles: ["candidate_id", "review_status"], notes: "Lists draft candidates without reading workspace files directly." },
  { command: "review apply", view: "production-semantic", handles: ["candidate_id", "review_status", "decision_payload"], notes: "Applies copied review decisions to the project ledger and approved knowledge." },
  { command: "review approve", view: "production-semantic", handles: ["candidate_id", "review_scope", "review_status"], notes: "Approves one draft candidate inside an explicit collection or all-candidate review scope." },
  { command: "review approve-all", view: "production-semantic", handles: ["candidate_id", "candidate_fingerprint", "review_scope", "review_status"], notes: "Atomically approves the validated current review scope under explicit current-conversation managed authority or the Route-bound user force-approval escape path." },
  { command: "review reject", view: "production-semantic", handles: ["candidate_id", "review_scope", "review_status"], notes: "Rejects one draft candidate inside an explicit collection or all-candidate review scope." },
  { command: "review deprecate", view: "production-semantic", handles: ["view_ref", "review_status"], notes: "Marks one approved ViewRef as deprecated without deleting files by hand." },

  { command: "close", view: "production-semantic", handles: ["project_status", "node_ref", "view_ref", "edge_count", "verify_status"], notes: "Derives approved structure and runs the final verify gate." },
  { command: "build", view: "production-semantic", handles: ["package_name", "build_inventory", "issue_code"], notes: "Builds declared project packages after close and verify gates." },
  { command: "source", view: "production-semantic", handles: ["source_name", "source_type", "source_status"], notes: "Project source registry namespace." },
  { command: "source add", view: "production-semantic", handles: ["source_name", "source_type"], notes: "Adds typed project source registry entries." },
  { command: "source add batch", view: "production-semantic", handles: ["date_batch", "module_name", "source_type", "local_checkout", "local_path", "lark_url", "lark_token"], notes: "Registers multiple repo, file, or Lark modules under one project write lock from YAML/JSON input." },
  { command: "source add file", view: "production-semantic", handles: ["date_batch", "module_name", "local_path", "include_glob"], notes: "Registers a local document module under a shared date batch." },
  { command: "source add lark", view: "production-semantic", handles: ["date_batch", "module_name", "lark_url", "lark_token"], notes: "Registers a Lark/Feishu document module under a shared date batch." },
  { command: "source add repo", view: "production-semantic", handles: ["source_name", "local_checkout", "git_ref"], notes: "Registers a repo source without mutating external repositories." },
  { command: "source ensure", view: "production-semantic", handles: ["source_name", "source_status", "git_ref"], notes: "Validates repo source readiness and returns agent hints instead of changing git state." },
  { command: "source recovery-plan", view: "production-semantic", handles: ["source_name", "local_checkout", "git_ref", "next_command"], notes: "Groups missing logical repo modules into physical checkout recovery decisions without scanning or cloning." },
  { command: "source restore", view: "production-semantic", handles: ["source_name", "local_checkout", "git_ref", "input_payload"], notes: "Restores registered repo sources from explicit local-path or clone decisions and rematerializes module links." },
  { command: "source list", view: "production-semantic", handles: ["source_name", "source_status"], notes: "Lists source registry metadata." },
  { command: "source get", view: "production-semantic", handles: ["source_name"], notes: "Shows one source registry entry." },
  { command: "source inspect", view: "production-semantic", handles: ["source_name", "module_name", "knowledge_path"], notes: "Inspects registered repo source boundaries and projected knowledge path examples." },
  { command: "source remove", view: "production-semantic", handles: ["source_name", "source_type", "source_status", "plan_digest"], notes: "Previews exact manifest-owned cleanup, then applies the digest-bound plan without deleting shared batch directories." },
  { command: "verify", view: "production-semantic", handles: ["issue_code", "node_ref", "view_ref", "section_id", "source_ref"], notes: "Validates the current project workspace." },
  { command: "clean-cache", view: "production-semantic", handles: ["removed_count", "cache_status"], notes: "Top-level local maintenance command for orphaned Claude plugin cache cleanup." },
] as const;
