import type { CommandMatrixEntry } from "./pathFreeContractTypes.js";

export const COMMAND_MATRIX: readonly CommandMatrixEntry[] = [
  { command: "entry", view: "production-semantic", handles: ["project_status", "workspace_root", "next_command"], notes: "Resolves the single agent entry into initialization, workspace relocation, or current Agent Graph workflow evaluation." },
  { command: "init", view: "production-semantic", handles: ["project_dir", "project_name"], notes: "Creates a project-local Context workspace." },
  { command: "plugin", view: "production-semantic", handles: ["plugin_status", "agent_adapter"], notes: "Global Context agent plugin namespace." },
  { command: "plugin install", view: "production-semantic", handles: ["plugin_status", "agent_adapter", "marketplace_root"], notes: "Installs or refreshes bundled global agent plugins." },
  { command: "plugin path", view: "production-semantic", handles: ["marketplace_root"], notes: "Prints the bundled plugin marketplace root." },
  { command: "plugin status", view: "production-semantic", handles: ["plugin_status", "agent_adapter"], notes: "Reports global plugin installation state and stale entry cleanup." },
  { command: "debug", view: "production-semantic", handles: ["trace_id", "debug_status"], notes: "Workspace-local observational trace namespace; disabled by default." },
  { command: "debug enable", view: "production-semantic", handles: ["trace_id", "debug_status"], notes: "Explicitly enables command and Agent Graph event recording below the ignored workspace runtime directory." },
  { command: "debug disable", view: "production-semantic", handles: ["trace_id", "debug_status"], notes: "Stops new event recording without deleting prior trace data." },
  { command: "debug status", view: "production-semantic", handles: ["trace_id", "debug_status", "event_count"], notes: "Reports debug configuration, event counts, and local trace locations." },
  { command: "debug export", view: "production-semantic", handles: ["trace_id", "event_count", "transition_count"], notes: "Deterministically projects append-only events into replay-ready JSON below the workspace runtime directory." },
  { command: "logs", view: "production-semantic", handles: ["delivery_status"], notes: "Hidden namespace for a configured package-owned runtime event sink." },
  { command: "logs plan", view: "production-semantic", handles: ["outbox", "event_summary", "sink_destination", "next_command"], notes: "Describes the fixed runtime-event payload source and package-owned sink without delivering data." },
  { command: "logs flush", view: "production-semantic", handles: ["delivery_status", "event_count", "next_command"], notes: "Flushes pending generic runtime events through the configured package-owned sink." },
  { command: "revise", view: "production-semantic", handles: ["view_ref", "revision_status", "next_command"], notes: "Starts one source-faithful conversational correction by approved title, path, ViewRef, NodeRef, or fragment id." },
  { command: "optimize-docs", view: "production-semantic", handles: ["optimization_status"], notes: "Document presentation optimization namespace for source-faithful package projections." },
  { command: "optimize-docs enable", view: "production-semantic", handles: ["optimization_status", "pending_count"], notes: "Enables workspace-local document optimization; revision pages are created only when content changes." },
  { command: "optimize-docs disable", view: "production-semantic", handles: ["optimization_status", "recovery_path"], notes: "Disables document optimization and moves prior revisions into recoverable runtime storage." },
  { command: "optimize-docs status", view: "production-semantic", handles: ["optimization_status", "pending_count", "conflict_count"], notes: "Reports fragment eligibility, revision freshness, and manual edit conflicts." },
  { command: "optimize-docs validate", view: "production-semantic", handles: ["optimization_status", "conflict_count"], notes: "Validates revision pages and reconciles safe manual edits without modifying approved knowledge." },
  { command: "optimize-docs plan", view: "production-semantic", handles: ["view_ref", "section_id", "source_ref", "input_payload"], notes: "Returns the digest-bound fragment batch that requires conservative Agent optimization." },
  { command: "optimize-docs apply", view: "production-semantic", handles: ["decision_payload", "optimization_status"], notes: "Atomically applies one complete digest-bound batch of keep, repair, reshape, or omit decisions." },
  { command: "optimize-docs revise", view: "production-semantic", handles: ["view_ref", "revision_status", "next_command"], notes: "Compatibility entry for starting one source-faithful conversational correction." },
  { command: "optimize-docs revise-current", view: "production-semantic", handles: ["view_ref", "section_id", "revision_status", "next_command"], notes: "Returns the active correction target and its validation step." },

  { command: "status", view: "production-semantic", handles: ["project_status", "source_name", "phase_id", "next_command"], notes: "Reports project lifecycle state and status-driven next actions." },
  { command: "resource", view: "production-semantic", handles: ["project_status"], notes: "Context workflow resource namespace." },
  { command: "resource acknowledge-current", view: "production-semantic", handles: ["project_status", "resource_digest", "next_command"], notes: "Records one merged current-conversation receipt set after the Agent reads every direct required resource." },
  { command: "resource materialize", view: "production-semantic", handles: ["project_status", "source_name", "phase_id", "next_command"], notes: "Materializes one route-selected Context view for the current workflow revision." },
  { command: "package", view: "production-semantic", handles: ["package_name", "package_status"], notes: "Package output configuration namespace." },
  { command: "package template", view: "production-semantic", handles: ["package_name", "template_status"], notes: "Package template review namespace." },
  { command: "package template accept", view: "production-semantic", handles: ["package_name", "template_status"], notes: "Explicitly accepts an unchanged generated starter template." },
  { command: "run", view: "production-semantic", handles: ["phase_id", "view", "source_ref", "node_ref", "view_ref", "input_payload"], notes: "Inspects, validates, stages, or executes declared project phases." },
  { command: "migrate", view: "production-semantic", handles: ["migration_status"], notes: "Workspace protocol migration namespace." },
  { command: "migrate codeindex", view: "production-semantic", handles: ["migration_status", "rewritten_files", "next_command"], notes: "Migrates one legacy codegraph workspace to the current codeindex protocol under the project write lock." },
  { command: "review", view: "production-semantic", handles: ["candidate_id", "review_status"], notes: "Review namespace for draft project candidates." },
  { command: "review html", view: "production-semantic", handles: ["candidate_id", "review_status", "source_ref"], notes: "Renders self-contained review UI and copyable review payload." },
  { command: "review list", view: "production-semantic", handles: ["candidate_id", "review_status"], notes: "Lists draft candidates without reading workspace files directly." },
  { command: "review apply", view: "production-semantic", handles: ["candidate_id", "review_status", "decision_payload"], notes: "Applies copied review decisions to the project ledger and approved knowledge." },
  { command: "review code-index", view: "production-semantic", handles: ["review_status", "decision_payload", "next_command"], notes: "Reads or resolves the mandatory batch-level Agent audit for code-index depth, evidence scope, source coverage, and handoffs." },
  { command: "review approve", view: "production-semantic", handles: ["candidate_id", "review_scope", "review_status"], notes: "Approves one draft candidate inside an explicit collection or all-candidate review scope." },
  { command: "review approve-all", view: "production-semantic", handles: ["candidate_id", "candidate_fingerprint", "review_scope", "review_status"], notes: "Atomically approves the validated current review scope under explicit current-conversation managed authority or the Route-bound user force-approval escape path." },
  { command: "review reconcile-identities", view: "production-semantic", handles: ["source_name", "node_ref", "view_ref", "next_command"], notes: "Preserves approved path identities before recompiling the affected source; identity migration is not implicit." },
  { command: "review reject", view: "production-semantic", handles: ["candidate_id", "review_scope", "review_status"], notes: "Rejects one draft candidate inside an explicit collection or all-candidate review scope." },
  { command: "review re-pin", view: "production-semantic", handles: ["view_ref", "source_ref"], notes: "Accepts document source drift by updating approved prose source_ref metadata for one approved ViewRef." },
  { command: "review deprecate", view: "production-semantic", handles: ["view_ref", "review_status"], notes: "Marks one approved ViewRef as deprecated without deleting files by hand." },
  { command: "review keep-orphaned", view: "production-semantic", handles: ["view_ref", "evidence_status"], notes: "Keeps one approved ViewRef when its source is intentionally unavailable while preserving a verification warning." },
  { command: "review maintain", view: "production-semantic", handles: ["view_ref", "source_ref", "evidence_status", "decision_payload"], notes: "Validates and atomically applies a typed batch of evidence-maintenance decisions." },

  { command: "close", view: "production-semantic", handles: ["project_status", "node_ref", "view_ref", "edge_count", "verify_status"], notes: "Derives approved structure and runs the final verify gate." },
  { command: "build", view: "production-semantic", handles: ["package_name", "build_inventory", "issue_code"], notes: "Builds declared project packages after close and verify gates." },
  { command: "source", view: "production-semantic", handles: ["source_name", "source_type", "source_status"], notes: "Project source registry namespace." },
  { command: "source add", view: "production-semantic", handles: ["source_name", "source_type"], notes: "Adds typed project source registry entries." },
  { command: "source add batch", view: "production-semantic", handles: ["date_batch", "module_name", "source_type", "local_checkout", "local_path", "lark_url", "lark_token"], notes: "Registers multiple repo, file, or Lark modules under one project write lock from YAML/JSON input." },
  { command: "source add file", view: "production-semantic", handles: ["date_batch", "module_name", "local_path", "include_glob"], notes: "Registers a local document module under a shared date batch." },
  { command: "source add lark", view: "production-semantic", handles: ["date_batch", "module_name", "lark_url", "lark_token"], notes: "Registers a Lark/Feishu document module under a shared date batch." },
  { command: "source add repo", view: "production-semantic", handles: ["source_name", "local_checkout", "git_ref"], notes: "Registers a repo source without mutating external repositories." },
  { command: "source ensure", view: "production-semantic", handles: ["source_name", "source_status", "git_ref"], notes: "Validates repo source readiness and returns agent hints instead of changing git state." },
  { command: "source recovery-plan", view: "production-semantic", handles: ["source_name", "local_checkout", "git_ref", "next_command"], notes: "Groups missing logical repo modules into physical checkout recovery decisions without scanning or cloning." },
  { command: "source restore", view: "production-semantic", handles: ["source_name", "local_checkout", "git_ref", "input_payload"], notes: "Restores registered repo sources from explicit local-path or clone decisions and rematerializes module links." },
  { command: "source list", view: "production-semantic", handles: ["source_name", "source_status"], notes: "Lists source registry metadata." },
  { command: "source get", view: "production-semantic", handles: ["source_name"], notes: "Shows one source registry entry." },
  { command: "source inspect", view: "production-semantic", handles: ["source_name", "module_name", "knowledge_path"], notes: "Inspects registered repo source boundaries and projected knowledge path examples." },
  { command: "source remove", view: "production-semantic", handles: ["source_name", "source_type", "source_status", "plan_digest"], notes: "Previews exact manifest-owned cleanup, then applies the digest-bound plan without deleting shared batch directories." },
  { command: "verify", view: "production-semantic", handles: ["issue_code", "node_ref", "view_ref", "section_id", "source_ref"], notes: "Validates the current project workspace." },
  { command: "clean-cache", view: "production-semantic", handles: ["removed_count", "cache_status"], notes: "Top-level local maintenance command for orphaned Claude plugin cache cleanup." },
] as const;
